name = "Starlit Minecraft"
author = "starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "872253e7fa9fc514dba00b707c841225c7674f629320654e19aeb0cfebfb4da0"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
