name = "Starlit Minecraft"
author = "starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7abbea347371146d4e14dd868953b6bac843cebddd4e78fb980852019b2cf62a"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
