name = "Starlit Minecraft"
author = "starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bef39b85e99b9e2131c9e0b3ef874bd3825acf29c866ed0fc99f2898fcc2a62b"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
