name = "Starlit Minecraft"
author = "starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1bc0680baa9b2a55d7b2f412525d8f8576d7b6a70e754b5bf98cab0686fdf00"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
