name = "Starlit Minecraft"
author = "starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "364864a66c08a4b57ce9cd610ebe6653fb25a1d412eaa11537bc935801d24c41"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
