name = "Starlit Minecraft"
author = "starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "478d4651ce622c7519130ceca02408a1a6a5b6a799fe6241555b03cd95c21718"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
