name = "Starlit Minecraft"
author = "starlightsys"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e49aed37bed5229dbe14b962056607c83d300c787ada5aca2854466770129a34"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
